In [ ]:
import pandas as pd
from google.colab import files
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [ ]:
from google.colab import files #позволяет с локального компьютера загрузить в колаб какие то файлы
uploaded = files.upload()
train=pd.read_csv('Social_Network_Ads.csv' )

Saving Social_Network_Ads.csv to Social_Network_Ads (9).csv

In [ ]:
train.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
# размерность данных
print(train.shape)
#какие типы данных представлены в наборе
print(train.info())
# df.isna() - проверку на пустые значение
print(train.isna().sum())

(400, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB
None
User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
#смотрим какие категориальные признаки есть в датасете

print(train['User ID'].unique())
print('_'*70)
print(train['Gender'].unique())
print('_'*70)
print(train['Age'].unique())
print('_'*70)
print(train['EstimatedSalary'].unique())
print('_'*70)
print(train['Purchased'].unique())
print('_'*70)

[15624510 15810944 15668575 15603246 15804002 15728773 15598044 15694829
 15600575 15727311 15570769 15606274 15746139 15704987 15628972 15697686
 15733883 15617482 15704583 15621083 15649487 15736760 15714658 15599081
 15705113 15631159 15792818 15633531 15744529 15669656 15581198 15729054
 15573452 15776733 15724858 15713144 15690188 15689425 15671766 15782806
 15764419 15591915 15772798 15792008 15715541 15639277 15798850 15776348
 15727696 15793813 15694395 15764195 15744919 15671655 15654901 15649136
 15775562 15807481 15642885 15789109 15814004 15673619 15595135 15583681
 15605000 15718071 15679760 15654574 15577178 15595324 15756932 15726358
 15595228 15782530 15592877 15651983 15746737 15774179 15667265 15655123
 15595917 15668385 15709476 15711218 15798659 15663939 15694946 15631912
 15768816 15682268 15684801 15636428 15809823 15699284 15786993 15709441
 15710257 15582492 15575694 15756820 15766289 15593014 15584545 15675949
 15672091 15801658 15706185 15789863 15720943 15697997 15665416 15660200
 15619653 15773447 15739160 15689237 15679297 15591433 15642725 15701962
 15811613 15741049 15724423 15574305 15678168 15697020 15610801 15745232
 15722758 15792102 15675185 15801247 15725660 15638963 15800061 15578006
 15668504 15687491 15610403 15741094 15807909 15666141 15617134 15783029
 15622833 15746422 15750839 15749130 15779862 15767871 15679651 15576219
 15699247 15619087 15605327 15610140 15791174 15602373 15762605 15598840
 15744279 15670619 15599533 15757837 15697574 15578738 15762228 15614827
 15789815 15579781 15587013 15570932 15794661 15581654 15644296 15614420
 15609653 15594577 15584114 15673367 15685576 15774727 15694288 15603319
 15759066 15814816 15724402 15571059 15674206 15715160 15730448 15662067
 15779581 15662901 15689751 15667742 15738448 15680243 15745083 15708228
 15628523 15708196 15735549 15809347 15660866 15766609 15654230 15794566
 15800890 15697424 15724536 15735878 15707596 15657163 15622478 15779529
 15636023 15582066 15666675 15732987 15789432 15663161 15694879 15593715
 15575002 15622171 15795224 15685346 15691808 15721007 15794253 15694453
 15813113 15614187 15619407 15646227 15660541 15753874 15617877 15772073
 15701537 15736228 15780572 15769596 15586996 15722061 15638003 15775590
 15730688 15753102 15810075 15723373 15795298 15584320 15724161 15750056
 15609637 15794493 15569641 15815236 15811177 15680587 15672821 15767681
 15600379 15801336 15721592 15581282 15746203 15583137 15680752 15688172
 15791373 15589449 15692819 15727467 15734312 15764604 15613014 15759684
 15609669 15685536 15750447 15663249 15638646 15734161 15631070 15761950
 15649668 15713912 15586757 15596522 15625395 15760570 15566689 15725794
 15673539 15705298 15675791 15747043 15736397 15678201 15720745 15637593
 15598070 15787550 15603942 15733973 15596761 15652400 15717893 15622585
 15733964 15753861 15747097 15594762 15667417 15684861 15742204 15623502
 15774872 15611191 15674331 15619465 15575247 15695679 15713463 15785170
 15796351 15639576 15693264 15589715 15769902 15587177 15814553 15601550
 15664907 15612465 15810800 15665760 15588080 15776844 15717560 15629739
 15729908 15716781 15646936 15768151 15579212 15721835 15800515 15591279
 15587419 15750335 15699619 15606472 15778368 15671387 15573926 15709183
 15577514 15778830 15768072 15768293 15654456 15807525 15574372 15671249
 15779744 15624755 15611430 15774744 15629885 15708791 15793890 15646091
 15596984 15800215 15577806 15749381 15683758 15670615 15715622 15707634
 15806901 15775335 15724150 15627220 15672330 15668521 15807837 15592570
 15748589 15635893 15757632 15691863 15706071 15654296 15755018 15594041]
______________________________________________________________________
['Male' 'Female']
______________________________________________________________________
[19 35 26 27 32 25 20 18 29 47 45 46 48 49 31 21 28 33 30 23 24 22 59 34
 39 38 37 42 40 36 41 58 55 52 60 56 53 50 51 57 44 43 54]
______________________________________________________________________
[ 19000  20000  43000  57000  76000  58000  84000 150000  33000  65000
  80000  52000  86000  18000  82000  25000  26000  28000  29000  22000
  49000  41000  23000  30000  74000 137000  16000  44000  90000  27000
  72000  31000  17000  51000 108000  15000  79000  54000 135000  89000
  32000  83000  55000  48000 117000  87000  66000 120000  63000  68000
 113000 112000  42000  88000  62000 118000  85000  81000  50000 116000
 123000  73000  37000  59000 149000  21000  35000  71000  61000  75000
  53000 107000  96000  45000  47000 100000  38000  69000 148000 115000
  34000  60000  70000  36000  39000 134000 101000 130000 114000 142000
  78000 143000  91000 144000 102000 126000 133000 147000 104000 146000
 122000  97000  95000 131000  77000 125000 106000 141000  93000 138000
 119000 105000  99000 129000  46000  64000 139000]
______________________________________________________________________
[0 1]
______________________________________________________________________

In [ ]:
label_encoder = preprocessing.LabelEncoder()
label_encoder.fit(train['Gender'])
train['Gender'] = label_encoder.transform(train['Gender'])
train

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [ ]:

from sklearn.model_selection import train_test_split
# train - на тренировочные
X = train.drop(['Purchased'], axis=1)
y = train['Purchased']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_st = scaler.fit_transform(X)
# fit()
# transform()

X_train_t, X_test_t, y_train_t, y_test_t = train_test_split(X,y, test_size=0.3)

# X - вектор признаков исходного набора
# X_st - вектор стандартизированных признаков
# X_norm - вектор нормализованных признаков

логистическая регрессия без маштабирования

In [ ]:
model = LogisticRegression()
# модель учится, для этого ей нужны ответы
model.fit(X_train, y_train)
# тестируем, для признаков у которых нет ответов, мы предсказывает ответ
answers_pred = model.predict(X_test)

In [ ]:
# Как оценить насколько хорошо работает ваша модель?

# answers_pred - ответы которые вернула модель для X_test
# y_test - это правильные ответы для X_test
print(accuracy_score(y_test,answers_pred))

0.8333333333333334

In [ ]:
# Уравнение регрессии
print('y = ')
[print(coef, end = "x + ") for coef in model.coef_[0]]
print(model.intercept_[0])

y =
-1.220814174680563e-07x + -3.878001330574615e-11x + 1.3245933734704029e-08x + 1.9610620078413363e-05x + -2.1655422841022044e-13

логистическая регрессия с маштабированием

In [ ]:
model = LogisticRegression()

model.fit(X_train_t, y_train_t)

answers_pred = model.predict(X_test_t)

In [ ]:
print(accuracy_score(y_test_t,answers_pred))

0.7666666666666667

метод ближайших соседей без маштабирования

In [ ]:
from sklearn.neighbors import KNeighborsClassifier


# создаем модель
# как подобрать лучшее число соседей?
scores = []
for i in range(1,15):

    knn = KNeighborsClassifier(i)
    # log = LogisticRegression()
    knn.fit(X_train,y_train)
    answers = knn.predict(X_test) # метод predict возвращыет вектор ответов для X_test

    scores.append(knn.score(X_test,y_test))
    # accuracy_score(y_test,answers)

print(scores)

[0.6416666666666667, 0.7333333333333333, 0.725, 0.7333333333333333, 0.725, 0.75, 0.7666666666666667, 0.7666666666666667, 0.75, 0.7333333333333333, 0.7416666666666667, 0.7583333333333333, 0.7833333333333333, 0.775]

In [ ]:
# для какого количества соседей оценка максимальна?
max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind

[12]

In [ ]:
knn = KNeighborsClassifier(13)

# обучаем
knn.fit(X_train, y_train)

# предсказываем значения
y_pred = knn.predict(X_test)

print(accuracy_score(y_test,y_pred))

0.7833333333333333

метод ближайших соседей c маштабированием

In [ ]:
from sklearn.neighbors import KNeighborsClassifier


# создаем модель
# как подобрать лучшее число соседей?
scores = []
for i in range(1,15):

    knn = KNeighborsClassifier(i)
    # log = LogisticRegression()
    knn.fit(X_train_t,y_train_t)
    answers = knn.predict(X_test_t) # метод predict возвращыет вектор ответов для X_test

    scores.append(knn.score(X_test_t,y_test_t))
    # accuracy_score(y_test,answers)

print(scores)

[0.6833333333333333, 0.725, 0.7166666666666667, 0.7666666666666667, 0.7666666666666667, 0.75, 0.7583333333333333, 0.75, 0.75, 0.7583333333333333, 0.7666666666666667, 0.7333333333333333, 0.75, 0.7333333333333333]

In [ ]:
max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind

[3, 4, 10]

In [ ]:
knn = KNeighborsClassifier(4)

knn.fit(X_train, y_train)


y_pred = knn.predict(X_test)

print(accuracy_score(y_test,y_pred))

0.7333333333333333

лучшим оказалось реализация модели логистической регрессии без маштабирования

худшим оказалось реализация метода ближайших соседей с маштабированием